- name: Change description on Nexus
  hosts: all
  become: yes
  tasks:
  - name: Configure interface settings 
    ios_interfaces:
      name: GigabitEthernet2/0/4
      description: Configured-by-Ansible Network
      authorize: yes 
      auth_pass: Deni1234