- name: Change description on Cisco interface
  hosts: all
  connection: network_cli
  become_method: enable
  gather_facts: yes

  tasks:
  - name: configure interface settings
  ios_config:
    lines:
      - description test interface
    parents: interface GigabitEthernet2/0/4