- name: Change description on Cisco interface
  hosts: all

  tasks:
  - name: Configure interface settings 
    ios_config:
      authorize: yes 
      usenrame: ansible
      password: Deni1234
      lines:
        - description test interface
      parents: interface GigabitEthernet2/0/4
