- name: Change description on Cisco interface
  hosts: all
  connection: local

  tasks:
  - name: Configure interface settings 
    ios_interface:
        name: GigabitEthernet2/0/4
        description: AnsibleWriten