- name: Change description on Nexus
  hosts: all
  become: yes
  tasks:
  - name: Configure interface settings 
    ios_config:
      lines:
        - description Configured by ansible
      parents: interface Ethernet1